version: 1.0.0.{build}-ci
skip_branch_with_pr: true
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj;**\*.props'
  version: '{version}'
  package_version: $(package_version)
  assembly_version: $(assembly_version)
  file_version: $(file_version)
  informational_version: $(informational_version)
install:
- ps: '& .\ci\set_version_from_git.ps1'
nuget:
  project_feed: true
  disable_publish_on_pr: true
cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml, codecov.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml, codecov.yml
before_build:
- ps: dotnet restore
- ps: choco install opencover.portable
- ps: choco install codecov
build:
  project: Rebus.Correlate.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
test_script:
  - OpenCover.Console.exe -target:"dotnet.exe" -targetargs:"test -c Debug" -output:coverage.xml -register:user -returntargetcode -filter:"+[*Rebus.Correlate*]* -[*Tests]*" -excludebyattribute:*.ExcludeFromCodeCoverageAttribute;*.GeneratedCodeAttribute;*.DebuggerNonUserCodeAttribute;*.CompilerGeneratedAttribute;*.DebuggerHiddenAttribute -oldStyle
  - codecov -f coverage.xml
deploy:
- provider: NuGet
  api_key:
    secure: V2QFEs9EHhZ5Fxgocpd0/jKOMhiFx1wXkLqPvs7DxSKJT9vItwFMwNQgI8yP1io+
  on:
    branch: /release/.*/
