version: 1.0.0.{build}-ci
skip_branch_with_pr: true
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj;**\*.props'
  version: '{version}'
  package_version: $(package_version)
  assembly_version: $(assembly_version)
  file_version: $(file_version)
  informational_version: $(informational_version)
install:
- ps: '& .\ci\set_version_from_git.ps1'
nuget:
  project_feed: true
  disable_publish_on_pr: true
before_build:
- ps: dotnet restore
build:
  project: Correlate.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
test:
  categories:
    except:
    - Integration
deploy:
- provider: NuGet
  api_key:
    secure: V2QFEs9EHhZ5Fxgocpd0/jKOMhiFx1wXkLqPvs7DxSKJT9vItwFMwNQgI8yP1io+
  on:
    branch: /release/.*/
